#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-munkres
Version  : 1.1.4
Release  : 31
URL      : https://files.pythonhosted.org/packages/fd/41/6a3d0ef908f47d07c31e5d1c2504388c27c39b10b8cf610175b5a789a5c1/munkres-1.1.4.tar.gz
Source0  : https://files.pythonhosted.org/packages/fd/41/6a3d0ef908f47d07c31e5d1c2504388c27c39b10b8cf610175b5a789a5c1/munkres-1.1.4.tar.gz
Summary  : Munkres (Hungarian) algorithm for the Assignment Problem
Group    : Development/Tools
License  : Apache-2.0
Requires: pypi-munkres-license = %{version}-%{release}
Requires: pypi-munkres-python = %{version}-%{release}
Requires: pypi-munkres-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3

%description
Introduction
        ============
        
        The Munkres module provides an implementation of the Munkres algorithm
        (also called the Hungarian algorithm or the Kuhn-Munkres algorithm),
        useful for solving the Assignment Problem.

%package license
Summary: license components for the pypi-munkres package.
Group: Default

%description license
license components for the pypi-munkres package.


%package python
Summary: python components for the pypi-munkres package.
Group: Default
Requires: pypi-munkres-python3 = %{version}-%{release}

%description python
python components for the pypi-munkres package.


%package python3
Summary: python3 components for the pypi-munkres package.
Group: Default
Requires: python3-core
Provides: pypi(munkres)

%description python3
python3 components for the pypi-munkres package.


%prep
%setup -q -n munkres-1.1.4
cd %{_builddir}/munkres-1.1.4
pushd ..
cp -a munkres-1.1.4 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1656392996
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 setup.py build

popd
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-munkres
cp %{_builddir}/munkres-1.1.4/LICENSE.md %{buildroot}/usr/share/package-licenses/pypi-munkres/4d875f3481bf2e7949fc4d79290552a3fff4818b
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -tt setup.py build install --root=%{buildroot}-v3
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-munkres/4d875f3481bf2e7949fc4d79290552a3fff4818b

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
